{
    answer_no: "Nein",
    answer_region_no: "Ich war in keiner der genannten Regionen",
    answer_unknown: "Ich weiß es nicht",
    answer_yes: "Ja",
    app_root_all_rights_reserved: "Alle Rechte vorbehalten.",
    app_root_data_privacy_link: "Datenschutzerklärung",
    app_root_faq_link: "FAQ",
    app_root_imprint_link: "Impressum",
    app_root_legal_link: "Rechtliches",
    button_continue: "Weiter zu den Fragen",
    button_delete_qr_code: "Fragebogen neu ausfüllen",
    button_show_code: "Erstellten QR-Code anzeigen",
    button_start_now: "Fragebogen starten",
    cookie_bar_accept: "Akzeptieren",
    cookie_bar_data_privacy: "Datenschutzerklärung",
    cookie_bar_reject: "Ablehnen",
    cookie_bar_text:
      "Mit Ihrer Einwilligung analysiert D4L data4life Ihre Nutzung der CovApp, um die CovApp für alle Nutzer zu verbessern. Wenn Sie in die Übermittlung von Analysedaten einwilligen möchten, klicken Sie bitte auf „Akzeptieren". Sie können die CovApp auch ohne Einwilligung in die Analyse Ihrer Nutzung der CovApp nutzen. Weitere Informationen finden Sie in der ",
    cookie_bar_text_dnt:
      'Für eine bessere Nutzererfahrung verwenden wir Cookies. Ihre "Do not track"-Browsereinstellung wird hierbei berücksichtigt und es findet keine Analyse statt.',
    data_privacy_content:
      '<strong>Hinweise zum Datenschutz bei der CovApp der Charité (Stand: 20.3.2020)</strong>\n\n<strong>1. Verantwortlichkeit</strong>\n\nDie CovApp ist ein Gemeinschaftsprojekt der Charité – Universitätsmedizin Berlin (Verantwortlich für die Bereitstellung und das Hosting der CovApp) und der gemeinnützigen D4L data4life gGmbH.\n\nFür die Verarbeitung personenbezogener Daten verantwortlich ist die\n\nCharité – Universitätsmedizin Berlin\nCharitéplatz 1\n10117 Berlin\nDeutschland\nTel: <a href="tel:+493045050">+49 (0) 30 450 50</a>\nWebsite: <a href="https://www.charite.de/" target="_blank">www.charite.de</a>\n\nBei Fragen zur Verarbeitung Ihrer personenbezogenen Daten, sowie zu Ihren Rechten rund um den Datenschutz, wenden Sie sich bitte an:\nTelefon: <a href="tel:+4930450580016">+49 (0) 30 450 580 016</a>\nE-Mail: <a href="mailto:datenschutz@charite.de">datenschutz(at)charite.de</a>\n\n<strong>2. Welche Daten werden erhoben und wie werden sie verarbeitet?</strong>\n\nMit der CovApp werden Fragen nach aktuellen Symptomen, Ihren letzten Reisen und möglichen Kontakten gestellt. Eine namentliche Zuordnung dieser Daten erfolgt nicht.\n\nBei der CovApp handelt es sich um Web-Anwendung. Dabei werden die folgenden Daten automatisch an den Web-Server der Charité, der im Auftrag der Charité von D4L data4life gGmbH als Auftragsverarbeiter betrieben wird, mit einem Rechenzentrum in Frankfurt bei dem Unterauftragsverarbeiter Amazon Web Services (AWS), übertragen:\n\nIP-Adresse des beim Abruf verwendeten Geräts\nWeb-Adresse (URL) der Seite, von der aus die Datei angefordert wurde (Referrer)\nDatum und Uhrzeit der Anforderung\nübertragene Datenmenge\nBeschreibung des Typs des verwendeten Webbrowsers\n\nDie oben genannten Daten werden nach der Verwendung der App nicht gespeichert, sodass kein Rückschluss auf die Identität des Nutzers/der Nutzerin möglich ist.\n\nDie Antworten auf die in der App beantworteten Fragen und die Handlungsempfehlungen werden ausschließlich lokal auf dem von Ihnen genutzten Endgerät (Smartphone, Tablet oder PC) gespeichert. Diese Daten werden - sofern Sie dies wünschen - in einem QR-Code zusammengefasst. Sie können diesen QR-Code bei einer Testung auf Covid-19, bei einem Arzt oder Krankenhaus vorzeigen, um die Erfassung von erforderlichen Anamnesedaten zu erleichtern.\n\nSie können die durch die CovApp auf ihrem Endgerät gespeicherten Daten jederzeit löschen, indem Sie am Ende des Fragebogens „Antworten löschen" anklicken. \n\n<strong>3. Zu welchen Zwecken und auf welcher Rechtsgrundlage werden die Daten verarbeitet?</strong>\n\nDie CovApp soll es den Nutzerinnen und Nutzern erleichtern, selbst einzuschätzen, ob ein weiterer Abklärungsbedarf hinsichtlich einer Covid-19 Infektion besteht und bietet konkrete Handlungsempfehlungen. Die App dient damit der Bekämpfung der aktuellen Covid-19 Pandemie. Rechtsgrundlage der Verarbeitung sind Artikel 6 Abs. 1 Satz 1 lit. d) und e), Art. 9 Abs. 2 lit c), h), i) Datenschutz-Grundverordnung in Verbindung mit § 14 Abs. 1 Nr. 3 Berliner Datenschutzgesetz.\n\n<strong>Im übrigen gilt die Datenschutzerklärung der Charité, abrufbar unter:</strong>\n<a href="https://www.charite.de/service/datenschutz/" target="_blank">https://www.charite.de/service/datenschutz/</a>',
    data_privacy_headline: "Datenschutzerklärung",
    disclaimer_headline: "Hinweis",
    disclaimer_paragraph_1:
      "Die Nutzung dieser App <strong>ersetzt keine ärztliche Behandlung und erbringt keine diagnostische Leistung</strong>. Die CovApp dient der Verbesserung der Handlungsabläufe in der Untersuchungsstelle der Charité und anderen Ambulanzen im Zusammenhang mit dem neuartigen Coronavirus SARS-CoV-2. \nWenn Sie sich aktuell schwer krank fühlen, suchen Sie bitte umgehend einen Arzt/Ärztin oder medizinische Hilfe auf.",
    disclaimer_paragraph_2:
      "Diese Website verwendet einen Cookie, welcher zur Handhabung der Website erforderlich ist. Persönliche Daten, die einen Rückschluss auf Ihre Person zulassen, werden nicht gespeichert.",
    disclaimer_sub_headline_1: "Hinweis auf die Verwendung von Cookies",
    faq_content:
      '<strong>Über das Coronavirus</strong>\nDie wissenschaftliche Bezeichnung des neuartigen Coronavirus lautet „SARS-CoV-2". Dieses Virus kann eine Atemwegserkrankung auslösen. Diese Erkrankung trägt den Namen „COVID-19". Weil sich die Infektionskrankheit COVID-19 bereits über Länder und Kontinente hinweg ausgebreitet hat, spricht man von einer Pandemie.\n \n<strong>Die Übertragung</strong>\nDas neuartige Coronavirus wird über die sogenannte Tröpfcheninfektion übertragen. Dies kann direkt von Mensch zu Mensch geschehen, wenn virushaltige Tröpfchen über die Mund- oder Nasenschleimhaut oder die Augenbindehaut in die Atemwege gelangen. Aber auch eine indirekte Ansteckung ist möglich, wenn Tröpfchen über die Hände mit den Schleimhäuten in Kontakt kommen. Krankheitszeichen treten im Durchschnitt nach 5 bis 6, maximal 14 Tagen nach einer Ansteckung auf.\n \n<strong>Die Krankheitszeichen</strong>\nWenn es zu einer Infektion mit dem Coronavirus gekommen ist, verläuft diese für die die meisten Menschen leicht und ist nicht lebensbedrohlich. Das gilt auch für Schwangere und Kinder. Leichte Krankheitszeichen können grippeähnliche Symptome wie trockener Husten, Abgeschlagenheit und Fieber sein. Darüber hinaus leiden einige Patient*innen unter Halskratzen, Kopf- und Gliederschmerzen und Schüttelfrost. Derzeit geht man davon aus, dass 4 von 5 Infektionen mild verlaufen. Bei einigen Betroffenen kann das Virus jedoch zu einem schwereren Verlauf mit Atemproblemen bis hin zur beidseitigen Lungenentzündung führen. Hier handelt es sich oftmals um ältere Menschen und Patientinnen und Patienten mit Vorerkrankungen wie Herz-Kreislauf-Erkrankungen, chronischen Atemwegserkrankungen, Diabetes, Bluthochdruck oder Krebs. Diese schweren Fälle müssen intensivmedizinisch im Krankenhaus behandelt werden. Wenn Sie sich krank fühlen, machen Sie den <a href="https://covapp.charite.de" target="_blank">Coronavirus – Test</a>.\n\n<strong>Solidarität</strong>\nObwohl Deutschland über ein sehr gutes Gesundheitssystem verfügt, ist dieses nicht auf einen steilen Anstieg insbesondere der intensiv medizinisch zu betreuenden Patientinnen und Patienten eingestellt. Gelingt es aber, den Anstieg schwerer Erkrankungen über einen längeren Zeitraum hinauszuzögern, werden Infizierte auch weiterhin gut versorgt werden können. Darum liegt das Hauptaugenmerk derzeit auf einer Entschleunigung der Infektionsrate. Dies kann nur gelingen, wenn alle Bürgerinnen und Bürger auf räumliche Distanz gehen. Zum Schutz, insbesondere der älteren Generation und chronisch Kranker, sollten alle darum die Situation ernst nehmen und soziale Kontakte so weit wie möglich einschränken. Versorgen Sie aber bitte ältere, hochbetagte oder chronisch kranke Angehörige oder Nachbarn und alleinstehende, hilfsbedürftige Menschen mit Lebensmitteln und Dingen des täglichen Bedarfs. Haben Sie ein offenes Ohr für ihre Sorgen und kommunizieren Sie miteinander – aber halten Sie dabei bitte 2 Meter Abstand. Handeln Sie solidarisch.\n\n<strong>Schutz</strong>\nUm die Verbreitung des Coronavirus zu entschleunigen, vermeiden Sie unbedingt Berührungen beispielsweise bei der Begrüßung und waschen Sie Ihre Hände regelmäßig und gründlich mindestens 20 Sekunden lang mit Wasser und Seife. Halten Sie beim Husten oder Niesen größtmöglichen Abstand – drehen Sie sich einfach von ihrem Gegenüber weg. Niesen Sie in die Armbeuge oder in ein Papiertaschentuch, das Sie danach immer entsorgen. Vermeiden Sie es, mit ihren Händen Mund, Augen oder Nase zu berühren. Teilen Sie Gegenstände, die Sie mit Ihrem Mund berühren, wie z.B. Tassen oder Flaschen, nicht mit anderen Personen. Bleiben Sie daheim.\n \n<strong>Therapie</strong>\nDie Behandlung der Infektion richtet sich nach der Schwere des Krankheitsbildes. Milde Fälle müssen nicht behandelt und können daheim auskuriert werden. Schwerere Lungenentzündungen werden z.B. durch die Gabe von Sauerstoff, den Ausgleich des Flüssigkeitshaushalts oder Antibiotikagabe zur Behandlung von bakteriellen Begleitinfektionen behandelt. Dies geschieht meistens im Krankenhaus.\n \n<strong>Impfung</strong>\nEs wird an der Entwicklung eines Impfstoffes gearbeitet. Momentan steht jedoch noch kein Impfstoff zur Verfügung, der vor dem neuartigen Coronavirus schützt.\n \n<strong>Bleiben Sie informiert!</strong>\nDas Bundesministerium für Gesundheit aktualisiert regelmäßig die Information zum Coronavirus:\n<a href="https://www.bundesgesundheitsministerium.de/coronavirus.html" target="_blank">https://www.bundesgesundheitsministerium.de/coronavirus.html</a>\n \nDer Charité-Wissenschaftler Prof. Dr. Christian Drosten hält sie im NDR-Podcast auf dem Laufenden:\n<a href="https://www.ndr.de/nachrichten/info/Corona-Podcast-Alle-Folgen-in-der-Uebersicht,podcastcoronavirus134.html" target_blank>https://www.ndr.de/nachrichten/info/Corona-Podcast-Alle-Folgen-in-der-Uebersicht,podcastcoronavirus134.html</a>',
    faq_headline: "FAQ Coronavirus",
    found_code: "Es wurde ein QR-Code gefunden",
    imprint_content:
      '<strong>Anbieter</strong>\nCharité – Universitätsmedizin Berlin\nZentrale Postanschrift: Charitéplatz 1, 10117 Berlin\nDie Charité – Universitätsmedizin Berlin ist eine Körperschaft des Öffentlichen Rechts. Sie wird durch den Vorstandsvorsitzenden gesetzlich vertreten.\n\n<strong>Kontakt</strong>\nFür Hinweise, Lob und Kritik schreiben Sie uns bitte eine Email an: <a href="mailto:covapp@charite.de">covapp@charite.de</a>\nInternet: <a href="https://www.charite.de" target="_blank">https://www.charite.de</a>\n\n<strong>Verantwortlicher im Sinne des Medienrechts</strong>\nProf. Dr. Heyo K. Kroemer, der Vorstandsvorsitzende der Charité – Universitätsmedizin Berlin\n\n<strong>Zuständige Aufsichtsbehörde</strong>\nDer Regierende Bürgermeister von Berlin - inkl. Wissenschaft und Forschung \nKontakt: <a href="https://www.berlin.de/rbmskzl/" target="_blank">https://www.berlin.de/rbmskzl/</a>\n\nSenatsverwaltung für Gesundheit, Pflege und Gleichstellung \nKontakt: <a href="https://www.berlin.de/sen/gpg/" target="_blank">https://www.berlin.de/sen/gpg/</a>\n\nUmsatzsteuer - Identifikationsnummer: DE 228847810',
    imprint_headline: "Impressum",
    input_date_error: "Ungültiges Datum. Bitte versuchen Sie es erneut.",
    input_date_error_future: "Das Datum darf nicht in der Zukunft liegen.",
    input_date_help:
      "Achten Sie darauf, ein vollständiges Datum im Format TT.MM.JJJJ einzugeben, das nicht in der Zukunft liegt. Beispiel: 09.03.2020",
    input_date_label: "Bitte geben Sie das Datum ein",
    input_date_placeholder: "TT.MM.JJJJ",
    legal_first_paragraph:
      "<p><strong>Rechtliche Hinweise </strong></p><p>Haftungsausschluss (Disclaimer) </p><p><strong>Allgemeiner Hinweis</strong></p><p>Die Nutzung dieser App ersetzt keine ärztliche Behandlung. Wenn Sie sich aktuell schwer krank fühlen, suchen Sie bitte umgehend medizinische Hilfe. </p><p><strong>Haftung für Inhalte </strong></p><p>Als Dienstanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Dienstanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. </p><p><strong>Haftung für Links</strong></p><p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. </p><p><strong>Urheberrecht </strong></p><p>Die durch den Dienstanbieter erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>",
    legal_headline: "Rechtliches",
    q01_option0: "Jünger als 40",
    q01_option1: "40-50",
    q01_option2: "51-60",
    q01_option3: "61-70",
    q01_option4: "71-80",
    q01_option5: "Über 80",
    q01_text: "Wie alt sind Sie?",
    q02_option0: "Allein wohnend",
    q02_option1:
      "Zusammen mit Familie, in einer Wohngemeinschaft oder betreuten Gemeinschaftseinrichtung",
    q02_text: "Wie ist Ihre aktuelle Wohnsituation?",
    q03_option0: "Im medizinischen Bereich",
    q03_option1:
      "In einer Gemeinschaftseinrichtung (Schule, Kita, Universität, Heim etc.)",
    q03_option2: "Nein, in keinem der genannten Bereiche",
    q03_text: "Sind Sie in einem der folgenden Bereiche tätig?",
    q04_text: "Rauchen Sie?",
    q05_text:
      "Sind Sie in den letzten 4 Wochen verreist? (innerhalb Deutschlands oder ins Ausland)",
    q06_text:
      "Haben Sie sich im Landkreis Heinsberg (Nordrhein-Westfalen) aufgehalten?",
    q07_text: "Waren Sie in den letzten 4 Wochen außerhalb Deutschlands?",
    q08_option0: "Italien",
    q08_option1: "Iran",
    q08_option2: "China",
    q08_option3: "Südkorea",
    q08_option4: "Frankreich",
    q08_option5: "Österreich",
    q08_option6: "Spanien",
    q08_option7: "USA",
    q08_option8: "Ich war in keinem der genannten Länder",
    q08_text: "Waren Sie in einem der folgenden Länder?",
    q09_option0:
      "Südtirol (entspricht Provinz Bozen) in der Region Trentino-Südtirol",
    q09_option1: "Region Emilia-Romagna",
    q09_option2: "Region Lombardei",
    q09_option3: "Stadt Vo in der Provinz Padua in der Region Venetien",
    q09_text: "Italien: Waren Sie in einer der folgenden Regionen?",
    q10_option0: "Provinz Ghom",
    q10_option1: "Teheran",
    q10_text: "Iran: Waren Sie in einer der folgenden Regionen?",
    q11_option0: "Provinz Hubei (inkl. Stadt Wuhan)",
    q11_text: "China: Waren Sie in einer der folgenden Regionen?",
    q12_option0: "Provinz Gyeongsangbuk-do (Nord-Gyeongsang)",
    q12_text: "Südkorea: Waren Sie in einer der folgenden Regionen?",
    q13_option0:
      "Region Grand Est (diese Region enthält Elsass, Lothringen und Champagne-Ardenne)",
    q13_text: "Frankreich: Waren Sie in einer der folgenden Regionen?",
    q14_option0: "Bundesland Tirol",
    q14_text: "Österreich: Waren Sie in einer der folgenden Regionen?",
    q15_option0: "Madrid",
    q15_text: "Spanien: Waren Sie in einer der folgenden Regionen?",
    q16_option0: "Bundesstaat New York",
    q16_option1: "Bundesstaat Washington",
    q16_option2: "Bundesstaat Kalifornien",
    q16_text: "USA: Waren Sie in einer der folgenden Regionen?",
    q17_text: "An welchem Tag sind Sie von Ihrer Reise zurückgekehrt?",
    q18_comment:
      "Enger Kontakt mit einem bestätigten Fall bedeutet:\n<ul><li>Kontakt von Angesicht zu Angesicht länger als 15 Minuten</li><li>Direkter, physischer Kontakt (Berührung, Händeschütteln, Küssen)</li><li>Länger als 15 Minuten direkt neben einer infizierten Person (weniger als 2 Meter) verbracht</li><li>Kontakt mit oder Austausch von Körperflüssigkeiten</li><li>Teilen einer Wohnung</li></ul>",
    q18_text: "Hatten Sie engen Kontakt zu einem bestätigtem Fall?",
    q19_comment:
      "Ein Verdachtsfall ist eine Person, die aktuell Fieber, Husten oder Atemnot hat und Kontakt zu einem bestätigten Fall hatte oder sich in einer Region mit gehäuften Coronavirus-Infektionen aufgehalten hat.\n\nEnger Kontakt mit einem Verdachtsfall bedeutet:\n<ul><li>Kontakt von Angesicht zu Angesicht länger als 15 Minuten</li><li>Direkter, physischer Kontakt (Berührung, Händeschütteln, Küssen)</li><li>Länger als 15 Minuten direkt neben einer infizierten Person (weniger als 2 Meter) verbracht</li><li>Kontakt mit oder Austausch von Körperflüssigkeiten</li><li>Teilen einer Wohnung</li></ul>",
    q19_text: "Hatten Sie engen Kontakt zu einem Verdachtsfall?",
    q20_text: "An welchem Tag war der letzte Kontakt?",
    q21_text: "Hatten Sie Fieber (über 38 °C) in den letzten 24 Stunden?",
    q22_text: "Hatten Sie Fieber (über 38 °C) in den letzten 4 Tagen?",
    q23_option0: "Weniger als 38 °C",
    q23_option1: "38 °C",
    q23_option2: "39 °C",
    q23_option3: "40 °C",
    q23_option4: "41 °C",
    q23_option5: "42 °C",
    q23_option6: "Über 42 °C",
    q23_option7: "Ich weiß es nicht",
    q23_text: "Wie hoch war die höchste Temperatur ca.?",
    q24_text: "Haben Sie Schüttelfrost?",
    q25_text: "Fühlen Sie sich schlapp oder abgeschlagen?",
    q26_text: "Haben Sie Gliederschmerzen?",
    q27_text: "Haben Sie anhaltenden Husten?",
    q28_text: "Haben Sie Schnupfen?",
    q29_text: "Haben Sie Durchfall?",
    q30_text: "Haben Sie Halsschmerzen?",
    q31_text: "Haben Sie Kopfschmerzen?",
    q32_text: "Sind Sie schneller außer Atem als sonst?",
    q33_text: "Seit wann haben Sie die Symptome?",
    q34_text:
      "Wurde bei Ihnen eine chronische Lungenerkrankung diagnostiziert?",
    q35_text: "Haben Sie Diabetes?",
    q36_text: "Wurde bei Ihnen eine Herzerkrankung diagnostiziert?",
    q37_text: "Wurde bei Ihnen Adipositas (Fettsucht) diagnostiziert?",
    q38_text: "Sind Sie schwanger?",
    q39_text: "Nehmen Sie aktuell Cortison ein (in Tablettenform)?",
    q40_comment:
      "Immunsuppresiva nehmen oder bekommen Sie nach einer Organtransplantation, während der Therapie einer Autoimmunerkrankung oder im Rahmen einer Chemotherapie.",
    q40_text: "Nehmen Sie aktuell Immunsuppressiva?",
    q41_text:
      "Haben Sie sich im Zeitraum von Oktober 2019 bis heute gegen Grippe impfen lassen?",
    q42_text: "An welchem Tag sind Sie von Ihrer Reise zurückgekehrt?",
    qr_code_button_reset: "Antworten löschen",
    qr_code_headline: "Zusammenfassung Ihrer Antworten",
    qr_code_hide_answers: "Antworten ausblenden",
    qr_code_paragraph:
      "Folgend finden Sie eine Übersicht Ihrer Antworten als Tabelle und QR-Code.\n\nFalls Sie den Hinweis erhalten haben, sich in einer Untersuchungsstelle vorzustellen, speichern Sie bitte den folgenden QR-Code und die Zusammenfassung der Fragen. Wenn möglich, drucken Sie die Zusammenfassung aus und zeigen Sie diese vor.\n\nWenn Sie das Haus verlassen, halten Sie ausreichend Abstand (mehr als 2 Meter) zu anderen Personen. Fassen Sie möglichst nichts an, und achten Sie auf die Regeln für richtiges Husten und Niesen.",
    qr_code_print: "Drucken",
    qr_code_show_answers: "Antworten anzeigen",
    questionnaire_button_generate_qr: "Fragebogen abschließen",
    questionnaire_button_next: "Weiter",
    recommendation_risk_high_additonal_info:
      "<strong>Charité-Standort Virchow in Wedding</strong>\nMittelallee 1 \nGeöffnet täglich 8 bis 16 Uhr\n\n<strong>Vivantes-Klinikum Prenzlauer Berg </strong>\nDiesterwegstraße \nMo-Fr: 10 bis 19 Uhr, Sa/So: 10 bis 17 Uhr\n\n<strong>Vivantes Wenckebach-Klinikum in Tempelhof </strong>\nAlbrechtstraße \nMo-Fr: 10 bis 19 Uhr, Sa/So: 10 bis 17 Uhr\n\n<strong>Evangelisches Krankenhaus Königin Elisabeth Herzberge in Lichtenberg </strong>\nHerzbergstraße 79, 10365 Berlin \nMo-Fr: 10 bis 19 Uhr, Sa/So: 10 bis 17 Uhr\n\n<strong>DRK Kliniken Berlin Westend (Ambulantes Diagnostikzentrum)</strong>\nSpandauer Damm 130, 14050 Berlin\nMo-Fr: 9 bis 15 Uhr\n\n<strong>Coronavirus-Ambulanz im Gemeinschaftskrankenhaus Havelhöhe</strong>\nHaus 16, Kladower Damm 221, Spandau \nMo-Fr von 9 bis 17 Uhr geöffnet. Die Telefonhotline ist von Mo-Fr von 8 bis 18 Uhr und Sa/So 9 bis 15:30 Uhr besetzt.",
    recommendation_risk_high_emoji_label: "Roter Kreis",
    recommendation_risk_high_headline: "Melden Sie sich",
    recommendation_risk_high_hide_info: "Untersuchungsstellen ausblenden",
    recommendation_risk_high_show_info: "Untersuchungsstellen anzeigen",
    recommendation_risk_high_text:
      '<p>Sie scheinen zur Risikogruppe zu gehören. \n\nWenn Sie möchten, melden Sie sich bei der Hotline der Senatsgesundheitsverwaltung (Tel. <a href="tel:+493090282828">030/9028 28 28</a>) oder stellen Sie sich in einer der Untersuchungsstellen vor.</p><p>Wenn Sie das Haus verlassen, halten Sie ausreichend Abstand (mehr als 2 Meter) zu anderen Personen, fassen Sie möglichst nichts an und achten Sie auf die <a href="https://www.infektionsschutz.de/hygienetipps/hygiene-beim-husten-und-niesen/" target="_blank">Regeln für richtiges Husten und Niesen</a>.\nBitte vermeiden Sie unnötige Kontakte zu anderen Personen und bleiben Sie nach Möglichkeit zu Hause. </p>',
    recommendation_risk_low_emoji_label: "Gelber Kreis",
    recommendation_risk_low_headline: "Achten Sie auf Ihre Händehygiene",
    recommendation_risk_low_text:
      '<p><strong>Sie waren in einem RKI-Risikogebiet oder hatten Kontakt zu einer Person mit bestätigter Coronavirus-Infektion oder einem Verdachtsfall. Bitte bleiben Sie zu Hause und vermeiden Sie unnötige Kontakte zu anderen Personen. </strong>\n\nSollten Ihre Symptome in den nächsten Tagen stärker werden oder Sie sich unsicher fühlen, melden Sie bei der Hotline der Senatsgesundheitsverwaltung (Tel. <a href="tel:+493090282828">030/9028 28 28</a>) oder in einer der Untersuchungsstellen. Sind Sie Berliner, können Sie auch einen Termin in der Charité-Corona-Videosprechstunde unter <a href="https://bit.ly/2U07tCq" target="_blank">https://bit.ly/2U07tCq</a>vereinbaren.\n\nVermeiden Sie unnötige Kontakte zu anderen Personen und bleiben Sie nach Möglichkeit zu Hause. Wenn Sie das Haus verlassen halten Sie ausreichend Abstand (mindestens 2 Meter) zu anderen Personen, fassen Sie möglichst nichts an und achten Sie auf die <a href="https://www.infektionsschutz.de/hygienetipps/hygiene-beim-husten-und-niesen/" target="_blank">Regeln für richtiges Husten und Niesen</a>.</p>',
    recommendation_risk_medium_emoji_label: "Orange Kreis",
    recommendation_risk_medium_headline:
      "Kurieren Sie sich aus und bleiben Sie ruhig",
    recommendation_risk_medium_text:
      '<p>Da Sie in keinem RKI-Risikogebiet waren und keinen Kontakt zu einem diagnostizierten Fall (oder Verdachtsfall) hatten, wird aktuell kein Abstrich auf das Coronavirus empfohlen. Bleiben Sie zuhause, kurieren Sie sich aus und vermeiden Sie unnötige Kontakte zu anderen Personen.\n<strong>Sollten Ihre Symptome in den nächsten Tagen stärker werden oder Sie sich unsicher fühlen, dann melden Sie sich zunächst telefonisch bei Ihrem Hausarzt oder dem Ärztlichen Bereitschaftsdienst (<a href="tel:+49116117">+49 116 117</a>) oder vereinbaren Sie einen Termin in der Online Sprechstunde von KRY unter: <a href="https://bit.ly/2QuCZGo" target="_blank">https://bit.ly/2QuCZGo</a></strong>\nWenn Sie das Haus verlassen, halten Sie ausreichend Abstand (mehr als 2 Meter) zu anderen Personen, fassen Sie möglichst nichts an und achten Sie auf die <a href="https://www.infektionsschutz.de/hygienetipps/hygiene-beim-husten-und-niesen/" target="_blank">Regeln für richtiges Husten und Niesen.</a></p>',
    recommendation_risk_slight_emoji_label: "Grüner Kreis",
    recommendation_risk_slight_headline: "Bleiben Sie daheim",
    recommendation_risk_slight_text:
      '<p>Es besteht derzeit kein Handlungsbedarf für Sie, da Sie:</p><ul><li>Keinen Kontakt zu einem bestätigten Fall hatten</li><li>In den letzten 14 Tagen in keinem Risikogebiet laut RKI waren</li><li>Keine Symptome haben</li></ul><p>Achten Sie vermehrt auf gute <a href="https://www.infektionsschutz.de/haendewaschen.html">Händehygiene</a>.</p><p>Wenn Sie das Haus verlassen, halten Sie ausreichend Abstand (mehr als 2 Meter) zu anderen Personen, fassen Sie möglichst nichts an, und achten Sie auf die Regeln für richtiges Husten und Niesen.</p>',
    start_headline: "Handlungsempfehlungen und Informationen zum Coronavirus",
    start_legal_paragraph:
      "<strong>Bei der digitalen Anwendung handelt es sich nicht um eine Anwendung, die diagnostische Leistungen erbringt. Die Anwendung dient der Vereinfachung der Handlungsabläufe in der Versorgung.</strong>",
    start_paragraph_1_option_1: "Ansprechpartner und Kontakte für Berlin",
    start_paragraph_1_option_2:
      "Entscheidungshilfe bezüglich Arztbesuch oder Coronavirus-Test",
    start_paragraph_1_option_3:
      "Verhaltensweisen zur Reduzierung des Infektionsrisikos",
    start_paragraph_1_option_4: "Optimierung der Patientenströme",
    start_paragraph_2:
      "<p>Die CovApp ist eine von der Charité in Zusammenarbeit mit Data4Life entwickelte Software, mit der Sie innerhalb weniger Minuten einen Fragenkatalog beantworten und daraus spezifische Handlungsempfehlungen erhalten. Dafür werden Ihnen Fragen nach aktuellen Symptomen, Ihren letzten Reisen und möglichen Kontakten gestellt. Diese App erbringt keine diagnostischen Leistungen. Sie erhalten aber nach Beantwortung des Fragenkatalogs konkrete Handlungsempfehlungen, Ansprechpartner und Kontakte sowie eine Zusammenfassung Ihrer Daten. Ziel ist es, die Patientenströme in Krankenhäuser und Untersuchungsstellen zu optimieren.</p><p>So kann Ihnen die CovApp helfen, die Notwendigkeit eines Arztbesuches oder Coronavirus-Tests besser einzuschätzen. Die medizinisch relevanten Informationen für ein etwaiges Arztgespräch werden am Ende für Sie zusammengefasst.</p><p><strong>Wie nutze ich die CovApp?</strong></p>\n<p><strong>1. Starten Sie die Befragung durch Klicken auf „Fragebogen starten"</strong></p>\n<p>Der Fragebogen nimmt ca. 5 Minuten Ihrer Zeit in Anspruch und stellt Ihnen Fragen zu aktuellen Symptomen, Vorerkrankungen, Reisen in Risikogebiete und Kontakt zu Verdachtsfällen. Versuchen Sie, die Fragen so genau wie möglich zu beantworten.</p>\n<p><strong>2. Fragenkatalog und Empfehlungen</strong></p>\n<p>Zum Abschluss der Befragung erhalten Sie eine Übersicht über Ihre Antworten und spezifische Handlungsempfehlungen wie z.B. <ul><li>Anruf bei einer der Hotlines des öffentlichen Gesundheitsdienstes</li>\n<li>Vorstellung beim Hausarzt</li>\n<li>Häusliche Isolierung</li>\n</ul></p><p><strong>3. Vorbereitung eines Arztgesprächs</strong></p>\n<p>Falls ein Arztgespräch notwendig sein sollte, bieten einige Untersuchungsstellen die Möglichkeit, Ihre Antworten über einen QR-Code einzuscannen (u.a. an der Charité). Der Einsatz eines QR-Codes zur Übermittlung relevanter medizinischer Informationen unterstützt die weiterführende Versorgung und hilft, die hohe Anzahl an Hilfe- bzw. Ratsuchenden schneller zu bearbeiten. \nFür einen Besuch bei Ihrem Hausarzt oder in einer anderen Untersuchungsstelle außerhalb der Charité drucken Sie die Zusammenfassung am Ende aus oder zeigen Sie diese bei Ihrem Arztbesuch vor. </p>",
    start_paragraph_3:
      "<p>Der Fragebogen ist anonym und wird nur auf Ihrem Endgerät (zum Beispiel Mobiltelefon) bearbeitet und gespeichert. Ihre Antworten werden nicht an uns oder über das Internet an Dritte übertragen.</p>",
    start_paragraph_4:
      "<p>Die Nutzung dieser App ersetzt keine ärztliche Behandlung. Wenn Sie sich aktuell schwer krank fühlen, suchen Sie bitte umgehend medizinische Hilfe auf.</p>",
    start_sub_headline_1: "Vorbereitung des Ihres Arztgespräches",
    start_sub_headline_2: "Was ist die CovApp?",
    start_sub_headline_3: "Welche Daten werden über das Internet übertragen?",
    start_sub_headline_4: "Im Zweifel zum Arzt!"
  },